Load and coerce data using schema
MastodonC/kixi.lapita pull request #10
Opened 2017-02-06 15:28 UTC by Eleonore9

**Aim**: I need to be able to load data with the right data type in each column, hence data coercion with schema

**Issue**: I takes a long time to run and fail -> issue #9

**Solution**:
* Investigate and schema validation seems to block -> Improve schema coercion
* Coercion faster, but dataset creation fails `ExceptionInfo Can't create dataset from incomplete maps` -> It must me due to missing data in a few rows

2017-02-08 13:25 UTC, acron0 requested changes

2017-02-08 13:25 UTC, acron0 commented on src/kixi/lapita.clj
> +  ([filename schema {:keys [print-errors write-errors remove-errors]}]
When you have an arity with optional additional 'options' it's usual that the version without (two-arity in this case) calls the version with (three-arity in this case), just with an empty options map:

```
(defn foo
  ([x y opts]
    ...)
  ([x y]
    (foo x y {}))
```

2017-02-08 13:25 UTC, acron0 commented on src/kixi/lapita.clj
> +       (write-csv! errors "data/records-with-data-coercion-issues.csv")
Either save in a temp (`/tmp') file or allow the user to specify a location.

2017-02-08 13:25 UTC, acron0 commented on src/kixi/lapita.clj
> +(comment (def repairs-data (csv-to-maps-coll "data/historic-repairs-2014-2015.csv"))
Do these still need to be here? Are they in tests now?

2017-02-08 13:45 UTC, Eleonore9 commented on src/kixi/lapita.clj
> +  ([filename schema {:keys [print-errors write-errors remove-errors]}]
Oh yes, that's true! Thanks!

2017-02-08 13:47 UTC, Eleonore9 commented on src/kixi/lapita.clj
> +(comment (def repairs-data (csv-to-maps-coll "data/historic-repairs-2014-2015.csv"))
Well, they're very handing for me. But I guess I should save those examples locally!

2017-02-08 14:10 UTC, acron0 requested changes

2017-02-08 14:10 UTC, acron0 commented on src/kixi/lapita.clj
> +                     :or {errors-filepath "test-data/records-with-data-coercion-issues.csv"}}]
This is still not a safe file path to assume. You either need to force them to specify a dir or create a temporary file using a safe method.

2017-02-08 14:10 UTC, acron0 commented on src/kixi/lapita.clj
>         (println "The records with data coercion issues were saved in 'data/records-with-data-coercion-issues.csv'"))
Output should use `errors-filepath`

2017-02-08 14:51 UTC, acron0 commented on src/kixi/lapita/schemas.clj
> +                      (with-meta coerced {:data-coercion :validated}))))
Could we avoid using metadata here and just return a map with `:results` and `:errors`?

2017-02-09 13:11 UTC, acron0 requested changes

2017-02-09 13:11 UTC, acron0 commented on src/kixi/lapita.clj
>  (comment (def repairs-data (load-csv "data/historic-repairs-2014-2015.csv"))
Remove these pls

2017-02-09 13:11 UTC, acron0 commented on src/kixi/lapita/schemas.clj
> +    (pmap (fn [d] (let [coerced (data-coercer d)]
I don't think you need this pmap at all now

2017-02-09 13:11 UTC, acron0 commented on src/kixi/lapita/schemas.clj
> +(def HousingRepairSchema
Move to tests

2017-02-09 13:11 UTC, acron0 commented on src/kixi/lapita.clj
> +  ([filename schema {:keys [print-errors write-errors errors-filepath remove-errors]}]
I wouldn't bother having `write-errors` and `errors-filepath`, just have `write-errors` and let it either be a path to write to or nil.

2017-02-09 14:44 UTC, Eleonore9 commented on src/kixi/lapita/schemas.clj
> +(def HousingRepairSchema
I'm not using it in the test. Would it be a good place for my schema?

2017-02-09 15:25 UTC, acron0 approved these changes
looking good!

2017-02-09 15:31 UTC, merged