Add fn for basic plotting capabilities
MastodonC/kixi.lapita pull request #20
Opened 2017-02-13 17:34 UTC by Eleonore9

Addresses issue #15

2017-02-14 10:31 UTC, acron0 requested changes

2017-02-14 10:31 UTC, acron0 commented on project.clj
> +                 [instaparse "1.4.3"]
Why instaparse?

2017-02-14 10:31 UTC, acron0 commented on src/kixi/lapita/plot.clj
> +                        (if (= min-x 0) 0 (dec min-x)))
What about if you want to include numbers < 0 ?

2017-02-14 10:31 UTC, acron0 commented on src/kixi/lapita/plot.clj
> +            {:domain      [0 (+ 5 (reduce max y-data))]
What about if you want to include numbers < 0 ?

2017-02-14 10:31 UTC, acron0 commented on src/kixi/lapita/plot.clj
> +(comment
Move to a test namespace pls

2017-02-14 10:41 UTC, Eleonore9 commented on project.clj
> +                 [instaparse "1.4.3"]
I think I need it for schema-contrib to work.

2017-02-14 10:42 UTC, Eleonore9 commented on src/kixi/lapita/plot.clj
> +            {:domain      [0 (+ 5 (reduce max y-data))]
Good point, I need to test that!

2017-02-14 10:43 UTC, Eleonore9 commented on src/kixi/lapita/plot.clj
> +                        (if (= min-x 0) 0 (dec min-x)))
Good point, I need to test that!

2017-02-14 10:43 UTC, Eleonore9 commented on src/kixi/lapita/plot.clj
> +(comment
ok

2017-02-14 16:56 UTC, acron0 requested changes

2017-02-14 16:56 UTC, acron0 commented on src/kixi/lapita/plot.clj
> +                                                 :plot-height 320}))
No need to include defaults in here if they occur in the other arity

2017-02-27 11:57 UTC, Eleonore9 commented on src/kixi/lapita/plot.clj
> +                        (if (= min-x 0) 0 (dec min-x)))
I think it works well enough for now with negative x-values

![test-plot](https://cloud.githubusercontent.com/assets/2502761/23360553/e10493d6-fce3-11e6-8b2a-128ad21b43a5.png)

2017-03-03 11:10 UTC, Eleonore9 commented on project.clj
> +                 [instaparse "1.4.3"]
I get this exception when I remove instaparse: https://gist.github.com/Eleonore9/df42f4a37c37927d4b7015408320043f

2017-03-03 11:17 UTC, acron0 requested changes

2017-03-03 11:17 UTC, acron0 commented on src/kixi/lapita/plot.clj
> +         all-data (transform-data-for-plot ds x-data y-data)
I'm not sure this is enough to constitute an entirely separate function

2017-03-03 11:17 UTC, acron0 commented on src/kixi/lapita/plot.clj
> +         plot ((bar-spec all-data 1 bar-width flip-point
Perhaps annotate these magic numbers. `1` is the amount of data series being displayed on the chart and `0` is the index of the series data.

2017-03-03 11:37 UTC, Eleonore9 commented on src/kixi/lapita/plot.clj
> +         plot ((bar-spec all-data 1 bar-width flip-point
Good idea!

2017-03-03 11:37 UTC, Eleonore9 commented on src/kixi/lapita/plot.clj
> +         all-data (transform-data-for-plot ds x-data y-data)
OK, I'll change that.

2017-03-03 12:00 UTC, acron0 approved these changes

2017-03-03 12:01 UTC, merged